Bug fixes and some improvements.
zeit/wait-for pull request #2
Opened 2018-07-11 23:32 UTC by mrothNET

Some fixes and improvement for your create tool. 

Please see the commits for details.

2018-07-11 23:40 UTC, pranaygp commented on wait-for.c
> +		fprintf(stderr, "error: to many arguments. See 'wait-for --help'.\n");
`to` -> `too`

2018-07-12 01:28 UTC, Qix- requested changes

2018-07-12 01:28 UTC, Qix- commented on Dockerfile
> +RUN rm -rf build && mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE-Release}" && cmake --build .
`.dockerignore` should be used instead, as the build directory shouldn't be included in the build context to begin with.

**EDIT** there is already a `.dockerignore` with the build directory removed. This is a no-op for properly implemented Docker clients and thus should be reverted.

2018-07-12 01:28 UTC, Qix- commented on wait-for.c
> +	}
Can be put inside the above `if` block and reduced to `if (!type_satisfied) { ... }`

2018-07-12 01:28 UTC, Qix- commented on wait-for.c
> +		"wait-for [<options>] <file>",
I'd prefer the actual options here instead of a catch-all options segment.

As-is, it should be `[options]`.

2018-07-12 01:28 UTC, Qix- commented on wait-for.c
> +		fprintf(stderr, "error: missing argument (the file to wait for). See 'wait-for --help'.\n");
`missing file argument` please - I realize that was a poor error message on my part :)

Also, it's pretty implied that `--help` should be the next step if someone is having usage issues, and IMO should be removed (as well as the message below). The Unix philosophy includes 'no output unless necessary' and I'd like to stick to that for this utility in particular.

2018-07-12 17:21 UTC, mrothNET commented
Incorporated your notes and suggestions and removed the Dockerfile commit (yes, the docker installation here was broken).

Hope you enjoy.

2018-07-12 17:26 UTC, Qix- requested changes
Looks much better - just a few more nits :)

2018-07-12 17:26 UTC, Qix- commented on README.md
> +$ git submodule update
To be complete:

```console
$ git submodule update --init --recursive
```

2018-07-12 17:26 UTC, Qix- commented on README.md
> +$ git submodule update
Same here :)

2018-07-12 17:26 UTC, Qix- commented on wait-for.c
> +		fprintf(stderr, "error: missing file argument (the file to wait for).\n");
Just make this `error: milling file argument` (no period, either)

2018-07-12 17:26 UTC, Qix- commented on wait-for.c
> +		fprintf(stderr, "error: too many arguments.\n");
- No period, please :)
- use `fputs("error: too many arguments.\n", stderr)` instead

2018-07-12 17:26 UTC, Qix- commented on wait-for.c
> +		fprintf(stderr, "error: missing file argument (the file to wait for).\n");
Also, use `fputs("error: missing file argument\n", stderr)` since no substitution is taking place.

2018-07-12 17:38 UTC, mrothNET commented
Ok, hard work... ;-)

2018-07-12 17:45 UTC, mrothNET commented
FYI: Updated.

2018-07-12 19:26 UTC, Qix- approved these changes
LGTM, compiles fine. Will let @pranaygp approve/merge.

Thanks @mrothNET :)

2018-07-13 05:43 UTC, pranaygp commented
This looks great @mrothNET 
Thanks! 🙌

2018-07-13 05:43 UTC, merged